export interface CountryCode {
    country: string;
    calling_code: string;
    flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
    { "country": "Afghanistan", "calling_code": "+93", "flag": "assets/images/flags/Afghanistan-Flag-icon.png" },
    { "country": "Albania", "calling_code": "+355", "flag": "assets/images/flags/Albania-Flag-icon.png" },
    { "country": "Algeria", "calling_code": "+213", "flag": "assets/images/flags/Algeria-Flag-icon.png" },
    { "country": "Andorra", "calling_code": "+376", "flag": "assets/images/flags/Andorra-Flag-icon.png" },
    { "country": "Angola", "calling_code": "+244", "flag": "assets/images/flags/Angola-Flag-icon.png" },
    { "country": "Antigua and Barbuda", "calling_code": "+1-268", "flag": "assets/images/flags/Antigua-and-Barbuda-icon.png" },
    { "country": "Argentina", "calling_code": "+54", "flag": "assets/images/flags/Argentina-Flag-icon.png" },
    { "country": "Armenia", "calling_code": "+374", "flag": "assets/images/flags/Armenia-Flag-icon.png" },
    { "country": "Australia", "calling_code": "+61", "flag": "assets/images/flags/Australia-Flag-icon.png" },
    { "country": "Austria", "calling_code": "+43", "flag": "assets/images/flags/Austria-Flag-icon.png" },
    { "country": "Azerbaijan", "calling_code": "+994", "flag": "assets/images/flags/Azerbaijan-Flag-icon.png" },
    { "country": "Bahamas", "calling_code": "+1-242", "flag": "assets/images/flags/Bahamas-Flag-icon.png" },
    { "country": "Bahrain", "calling_code": "+973", "flag": "assets/images/flags/Bahrain-Flag-icon.png" },
    { "country": "Bangladesh", "calling_code": "+880", "flag": "assets/images/flags/Bangladesh-Flag-icon.png" },
    { "country": "Barbados", "calling_code": "+1-246", "flag": "assets/images/flags/Barbados-Flag-icon.png" },
    { "country": "Belarus", "calling_code": "+375", "flag": "assets/images/flags/Belarus-Flag-icon.png" },
    { "country": "Belgium", "calling_code": "+32", "flag": "assets/images/flags/Belgium-Flag-icon.png" },
    { "country": "Belize", "calling_code": "+501", "flag": "assets/images/flags/Belize-Flag-icon.png" },
    { "country": "Benin", "calling_code": "+229", "flag": "assets/images/flags/Benin-Flag-icon.png" },
    { "country": "Bhutan", "calling_code": "+975", "flag": "assets/images/flags/Bhutan-Flag-icon.png" },
    { "country": "Bolivia", "calling_code": "+591", "flag": "assets/images/flags/Bolivia-Flag-icon.png" },
    { "country": "Bosnia and Herzegovina", "calling_code": "+387", "flag": "assets/images/flags/Bosnian-Flag-icon.png" },
    { "country": "Botswana", "calling_code": "+267", "flag": "assets/images/flags/Botswana-Flag-icon.png" },
    { "country": "Brazil", "calling_code": "+55", "flag": "assets/images/flags/Brazil-Flag-icon.png" },
    { "country": "Brunei Darussalam", "calling_code": "+673", "flag": "assets/images/flags/Brunei-Flag-icon.png" },
    { "country": "Bulgaria", "calling_code": "+359", "flag": "assets/images/flags/Bulgaria-Flag-icon.png" },
    { "country": "Burkina Faso", "calling_code": "+226", "flag": "assets/images/flags/Burkina-Faso-Flag-icon.png" },
    { "country": "Burundi", "calling_code": "+257", "flag": "assets/images/flags/Burundi-Flag-icon.png" },
    { "country": "Cape Verde", "calling_code": "+238", "flag": "assets/images/flags/Cape-Verde-Flag-icon.png" },
    { "country": "Cambodia", "calling_code": "+855", "flag": "assets/images/flags/Cambodia-Flag-icon.png" },
    { "country": "Cameroon", "calling_code": "+237", "flag": "assets/images/flags/Cameroon-Flag-icon.png" },
    { "country": "Canada", "calling_code": "+1", "flag": "assets/images/flags/Canada-Flag-icon.png" },
    { "country": "Central African Republic", "calling_code": "+236", "flag": "assets/images/flags/CentralAfricanRepublic-icon.png" },
    { "country": "Chad", "calling_code": "+235", "flag": "assets/images/flags/Chad-Flag-icon.png" },
    { "country": "Chile", "calling_code": "+56", "flag": "assets/images/flags/Chile-Flag-icon.png" },
    { "country": "China", "calling_code": "+86", "flag": "assets/images/flags/China-Flag-icon.png" },
    { "country": "Colombia", "calling_code": "+57", "flag": "assets/images/flags/Colombia-Flag-icon.png" },
    { "country": "Comoros", "calling_code": "+269", "flag": "assets/images/flags/Comoros-Flag-icon.png" },
    { "country": "Congo", "calling_code": "+242", "flag": "assets/images/flags/Congo-Flag-icon.png" },
    { "country": "Congo, Democratic Republic of the", "calling_code": "+243", "flag": "assets/images/flags/Congo-Kinshasa-icon.png" },
    { "country": "Cook Islands", "calling_code": "+682", "flag": "assets/images/flags/Cook-Islands-icon.png" },
    { "country": "Costa Rica", "calling_code": "+506", "flag": "assets/images/flags/Costa-Rica-Flag-icon.png" },
    { "country": "Croatia", "calling_code": "+385", "flag": "assets/images/flags/Croatian-Flag-icon.png" },
    { "country": "Cuba", "calling_code": "+53", "flag": "assets/images/flags/Cuba-Flag-icon.png" },
    { "country": "Cyprus", "calling_code": "+357", "flag": "assets/images/flags/Cyprus-Flag-icon.png" },
    { "country": "Czechia", "calling_code": "+420", "flag": "assets/images/flags/Czech-Republic-Flag-icon.png" },
    { "country": "Denmark", "calling_code": "+45", "flag": "assets/images/flags/Denmark-Flag-icon.png" },
    { "country": "Djibouti", "calling_code": "+253", "flag": "assets/images/flags/Djibouti-Flag-icon.png" },
    { "country": "Dominica", "calling_code": "+1-767", "flag": "assets/images/flags/Dominicana-icon.png" },
    { "country": "Georgia", "calling_code": "+995", "flag": "assets/images/flags/Georgia-Flag-icon.png" },
    { "country": "India", "calling_code": "+91", "flag": "assets/images/flags/India-Flag-icon.png" },
    { "country": "Indonesia", "calling_code": "+62", "flag": "assets/images/flags/Indonesia-Flag-icon.png" },
    { "country": "Iran", "calling_code": "+98", "flag": "assets/images/flags/Iran-Flag-icon.png" },
    { "country": "Iraq", "calling_code": "+964", "flag": "assets/images/flags/Iraq-Flag-icon.png" },
    { "country": "Israel", "calling_code": "+972", "flag": "assets/images/flags/Israel-Flag-icon.png" },
    { "country": "Japan", "calling_code": "+81", "flag": "assets/images/flags/Japan-Flag-icon.png" },
    { "country": "Jordan", "calling_code": "+962", "flag": "assets/images/flags/Jordan-Flag-icon.png" },
    { "country": "Kazakhstan", "calling_code": "+7", "flag": "assets/images/flags/Kazakhstan-Flag-icon.png" },
    { "country": "Kuwait", "calling_code": "+965", "flag": "assets/images/flags/Kuwait-Flag-icon.png" },
    { "country": "Kyrgyzstan", "calling_code": "+996", "flag": "assets/images/flags/Kyrgyzstan-Flag-icon.png" },
    { "country": "Lao People's Democratic Republic", "calling_code": "+856", "flag": "assets/images/flags/Laos-Flag-icon.png" },
    { "country": "Lebanon", "calling_code": "+961", "flag": "assets/images/flags/Lebanon-Flag-icon.png" },
    { "country": "Malaysia", "calling_code": "+60", "flag": "assets/images/flags/Malaysia-Flag-icon.png" },
    { "country": "Maldives", "calling_code": "+960", "flag": "assets/images/flags/Maldives-Flag-icon.png" },
    { "country": "Mongolia", "calling_code": "+976", "flag": "assets/images/flags/Mongolia-Flag-icon.png" },
    { "country": "Myanmar", "calling_code": "+95", "flag": "assets/images/flags/Myanmar-icon.png" },
    { "country": "Nepal", "calling_code": "+977", "flag": "assets/images/flags/Nepal-Flag-icon.png" },
    { "country": "Oman", "calling_code": "+968", "flag": "assets/images/flags/Oman-Flag-icon.png" },
    { "country": "Pakistan", "calling_code": "+92", "flag": "assets/images/flags/Pakistan-Flag-icon.png" },
    { "country": "Palestine", "calling_code": "+970", "flag": "assets/images/flags/Palestinian-Territory-icon.png" },
    { "country": "Philippines", "calling_code": "+63", "flag": "assets/images/flags/Philippines-Flag-icon.png" },
    { "country": "Qatar", "calling_code": "+974", "flag": "assets/images/flags/Qatar-Flag-icon.png" },
    { "country": "Republic of Korea", "calling_code": "+82", "flag": "assets/images/flags/Korea-Flag-icon.png" },
    { "country": "Russian Federation", "calling_code": "+7", "flag": "assets/images/flags/Russia-Flag-icon.png" },
    { "country": "Saudi Arabia", "calling_code": "+966", "flag": "assets/images/flags/Saudi-Arabia-Flag-icon.png" },
    { "country": "Singapore", "calling_code": "+65", "flag": "assets/images/flags/Singapore-Flag-icon.png" },
    { "country": "Sri Lanka", "calling_code": "+94", "flag": "assets/images/flags/Sri-Lanka-Flag-icon.png" },
    { "country": "Syrian Arab Republic", "calling_code": "+963", "flag": "assets/images/flags/Syria-Flag-icon.png" },
    { "country": "Tajikistan", "calling_code": "+992", "flag": "assets/images/flags/Tajikistan-Flag-icon.png" },
    { "country": "Thailand", "calling_code": "+66", "flag": "assets/images/flags/Thailand-Flag-icon.png" },
    { "country": "Timor-Leste", "calling_code": "+670", "flag": "assets/images/flags/Timor-Leste-Flag-icon.png" },
    { "country": "Turkey", "calling_code": "+90", "flag": "assets/images/flags/Turkey-Flag-icon.png" },
    { "country": "Turkmenistan", "calling_code": "+993", "flag": "assets/images/flags/Turkmenistan-Flag-icon.png" },
    { "country": "United Arab Emirates", "calling_code": "+971", "flag": "assets/images/flags/United-Arab-Emirates-icon.png" },
    { "country": "Uzbekistan", "calling_code": "+998", "flag": "assets/images/flags/Uzbekistan-Flag-icon.png" },
    { "country": "Viet Nam", "calling_code": "+84", "flag": "assets/images/flags/Vietnam-Flag-icon.png" },
    { "country": "Yemen", "calling_code": "+967", "flag": "assets/images/flags/Yemen-Flag-icon.png" }
];
